//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SekerWeb.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Besin
    {
        public int iD { get; set; }
        public string Kahvaltı { get; set; }
        public string AraOgun { get; set; }
        public string Oglen { get; set; }
        public string OgleAraOgun { get; set; }
        public string Aksam { get; set; }
        public string AksamAraOgun { get; set; }
        public Nullable<int> HastaİD { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    
        public virtual Hasta Hasta { get; set; }
    }
}
