//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SekerWeb.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Duyuru
    {
        public int İD { get; set; }
        public string Duyurular { get; set; }
        public string Konu { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    }
}
