//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SekerWeb.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sekerlerim
    {
        public int İD { get; set; }
        public Nullable<int> HastaİD { get; set; }
        public Nullable<int> SabahAclik { get; set; }
        public Nullable<int> SabahTokluk { get; set; }
        public Nullable<int> OglenAclik { get; set; }
        public Nullable<int> OglenTokluk { get; set; }
        public Nullable<int> AksamAclık { get; set; }
        public Nullable<int> AksamTokluk { get; set; }
        public Nullable<int> Gece { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    
        public virtual Hasta Hasta { get; set; }
    }
}
