//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SekerWeb.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urun()
        {
            this.Sepetim = new HashSet<Sepetim>();
        }
    
        public int İd { get; set; }
        public string UrunAdı { get; set; }
        public Nullable<int> Fiyat { get; set; }
        public Nullable<int> KategoriİD { get; set; }
        public Nullable<int> MarkaİD { get; set; }
        public string Detay { get; set; }
        public string Resim { get; set; }
        public byte[] IMAGE { get; set; }
    
        public virtual Kategori Kategori { get; set; }
        public virtual Marka Marka { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sepetim> Sepetim { get; set; }
    }
}
