//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SekerWeb.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urun
    {
        public int İd { get; set; }
        public string UrunAdı { get; set; }
        public Nullable<int> Fiyat { get; set; }
        public Nullable<int> KategoriİD { get; set; }
        public Nullable<int> MarkaİD { get; set; }
        public string Detay { get; set; }
    
        public virtual Kategori Kategori { get; set; }
        public virtual Marka Marka { get; set; }
    }
}
